[package]
name = "apollo"
version = "0.1.0"
authors = ["Sami Timsina <stimsina@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
structopt = "0.3.21"
rustyline = "8.0.0"
colored = "2"
